/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pds_bzip2_Bzip2Activity */

#ifndef _Included_com_pds_bzip2_Bzip2Activity
#define _Included_com_pds_bzip2_Bzip2Activity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_pds_bzip2_Bzip2Activity_READ_EXTERNAL_STORAGE
#define com_pds_bzip2_Bzip2Activity_READ_EXTERNAL_STORAGE 0L
/*
 * Class:     com_pds_bzip2_Bzip2Activity
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pds_bzip2_Bzip2Activity_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
