/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pds_fmod_MainActivity */

#ifndef _Included_com_pds_fmod_MainActivity
#define _Included_com_pds_fmod_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pds_fmod_MainActivity
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_pds_fmod_MainActivity_fix
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
