package com.pds.flutter;

import android.graphics.PixelFormat;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;

import com.alibaba.android.arouter.facade.annotation.Route;
import com.pds.router.module.ModuleGroupRouter;

import io.flutter.view.FlutterView;

/**
 * A {@link Fragment} managing a {@link FlutterView}.
 *
 * <p><strong>Warning:</strong> This file is auto-generated by Flutter tooling.
 * DO NOT EDIT.</p>
 */
@Route(path = ModuleGroupRouter.FLUTTER_FRAGMENT)
public class FFragment extends Fragment {
    public static final String ARG_ROUTE = "route";
    private String mRoute = "/";

    private FlutterView mFlutterView;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mRoute = getArguments().getString(ARG_ROUTE);
        }
    }

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        mFlutterView = Flutter.createView(getActivity(), getLifecycle(), mRoute);
        // 解决黑屏问题
        mFlutterView.setZOrderOnTop(true);
        mFlutterView.getHolder().setFormat(PixelFormat.TRANSLUCENT);
        return mFlutterView;
    }

    public boolean onBackPressed() {
        if (mFlutterView != null) {
            mFlutterView.popRoute();
            return true;
        } else {
            return false;
        }
    }
}
